#https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=vsts&tabs=yaml

variables:
    year: $(Date:yyyy)
    month: $(Date:MM)
    day: $(Date:dd)
    uk: $(Date:yyyyMMdd)
    messagePush: $(Build.SourceVersionMessage)

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:


- job: FullTestOnLinux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self #skip checking out the default repository resource
      clean: true
  
    
    - script: |
        
        cd dockerize
        ls -l
        chmod 777 ./ci_test.bat 
        ./ci_test.bat
        
        docker image ls
        docker container ls
        cp -r -v ./jest-stare  $(Build.ArtifactStagingDirectory)/jest-stare/ 
        cp ./junit.xml  $(Build.ArtifactStagingDirectory)/junit.xml 
        cp ./cobertura-coverage.xml $(Build.ArtifactStagingDirectory)/cobertura-coverage.xml 
      displayName: test DDD

    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: '$(Build.ArtifactStagingDirectory)/junit.xml'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(Build.ArtifactStagingDirectory)/cobertura-coverage.xml'
    
    
    - script: |
        
        cd dockerize
        ls -l
        chmod 777 ./build_console.bat
        ./build_console.bat
        echo ' done console bat'
        docker image ls
        docker container ls

        pwd
        ls -lh
        echo ' mkdir'
        mkdir $(Build.ArtifactStagingDirectory)/console
        echo ' copy to artifacts'
        cp ./data-to-code-console-win.exe  $(Build.ArtifactStagingDirectory)/console/data-to-code-console-win.exe
        cp ./data-to-code-console-linux  $(Build.ArtifactStagingDirectory)/console/data-to-code-console-linux
        cp ./data-to-code-console-macos  $(Build.ArtifactStagingDirectory)/console/data-to-code-console-macos
        echo 'finish copy'
      displayName: console artifacts 
    
    
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: DataArtifacts
      displayName: 'Publish Artifact: drop' 
    
