name: Automatic Build Generator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAngular:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1] #[10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: build angular
      run: | 
          cd frontend/angular
          npm install -g @angular/cli
          npm i          
          ng build --buildOptimizer=true --aot=true --outputPath=buildAngular  --prod=true
          ls -lh buildAngular

    - name: copy angular output
      run: |
           cp -r frontend/angular/buildAngular buildAngular
           ls -lh buildAngular

    - name: make artifact angular
      uses: actions/upload-artifact@v2
      with:
        name: angularBuild
        path: buildAngular/ 
        retention-days: 1
  
  buildNetCore:
    
    runs-on: windows-latest
    needs: buildAngular
    
    steps:
    - uses: actions/checkout@v2

    - name: download angular build
      uses: actions/download-artifact@v2
      with:
        name: angularBuild
        path: buildAngular

    #- run: dir 
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.8.2,]'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100 #3.1.301

    - name: build backend 
      run: | 
          dir
          xcopy buildAngular\*.* backend\GenerateFromDB\wwwroot\ /Y /S
          cd backend
          dotnet tool restore
          dotnet pwsh -File ./configuration.ps1
          dotnet restore
          dotnet build
          cd GenerateFromDB
          # dotnet publish -r win-x64 -c release --self-contained -o publish
          # dotnet publish -r win-x64 -c release -o publish -p:PublishSingleFile=true -p:PublishTrimmed=true
          dotnet publish -r win-x64 -c release -o publish --self-contained 
          
          echo 'publish mac'
          dotnet publish -r osx-x64 -c debug -o publishMac -p:UseAppHost=true
          
          # add template to mac
          
          mkdir publishMac\wwwroot\GenerateAll\
          # dir wwwroot\
          # dir wwwroot\GenerateAll\
          xcopy wwwroot\GenerateAll publishMac\wwwroot\GenerateAll /S

          # add template to win

          mkdir publish\wwwroot\GenerateAll\
          # dir wwwroot\
          # dir wwwroot\GenerateAll\
          xcopy wwwroot\GenerateAll publish\wwwroot\GenerateAll /S
          tar.exe -a -c -f GenerateFromDB.zip publish
          
    #- run: dir 

    
    - name: upload asp.net core  Win
      uses: actions/upload-artifact@v2
      with:
        name: aspnetCoreWindows
        path: backend/GenerateFromDB/publish 
        retention-days: 1


    - name: upload zip with .net core
      uses: actions/upload-artifact@v2
      with:
        name: preparedForWPF
        path: backend/GenerateFromDB/GenerateFromDB.zip 
        retention-days: 1

    - name: build WPF single
      run: | 
          cd backend
          # del GenerateAppWPF\GenerateFromDB.zip 
          xcopy GenerateFromDB\GenerateFromDB.zip GenerateAppWPF\GenerateFromDB.zip /Y
          cd GenerateAppWPF          
          dotnet build -r win-x64 -c release -o WPF
          # dotnet publish -r win-x64 -c release -o WPF

    - name: upload wpf
      uses: actions/upload-artifact@v2
      with:
        name: WPF
        path: backend/GenerateAppWPF/WPF
        retention-days: 1

    - name: build WPF clickonce
      run: | 
          cd backend
          # del GenerateAppWPF\GenerateFromDB.zip 
          xcopy GenerateFromDB\GenerateFromDB.zip GenerateAppWPF\GenerateFromDB.zip /Y
          cd GenerateAppWPF          
          
          msbuild  /target:publish /p:PublishProfile=Properties\PublishProfiles\DataToCode.pubxml /p:OutputPath=WPFAPP
          # copy WPFAPP\GenerateAppWPF.application WPFAPP\GenerateAppWPF_.application

    - name: upload wpf app
      uses: actions/upload-artifact@v2
      with:
        name: WPFAppToDeploy
        path: backend/GenerateAppWPF/WPFAPPapp.publish
        retention-days: 1

    # - name: build backend mac
    #   run: | 
    #       dir
    #       cd backend
    #       cd GenerateFromDB
    #       dotnet build -r osx-x64
    #       dotnet publish -r osx-x64 -c release -o publishMac --self-contained 
    #       mkdir publishMac\wwwroot\GenerateAll\
    #       dir wwwroot\
    #       dir wwwroot\GenerateAll\
    #       xcopy wwwroot\GenerateAll publishMac\wwwroot\GenerateAll /S

    - name: upload asp.net core Mac
      uses: actions/upload-artifact@v2
      with:
        name: aspnetCoreMac
        path: backend/GenerateFromDB/publishMac 
        retention-days: 1
