# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAngular:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1] #[10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: | 
          npm install -g @angular/cli
          npm i
          ng build --buildOptimizer=true --aot=true --outputPath=buildAngular  --prod=true
    
    - run: ls -lh buildAngular

    - uses: actions/upload-artifact@v2
      with:
        name: angularBuild
        path: buildAngular/ 
  
  buildNetCore:
    
    runs-on: windows-latest
    needs: buildAngular
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: angularBuild
        path: buildAngular

    - run: dir 
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100 #3.1.301

    - run: | 
          cd backend
          dotnet restore
          dotnet build
          cd GenerateFromDB
          dotnet publish -r win-x64 -c release --self-contained -o publish

    - run: dir 
